name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Clear previous dependencies
        run: |
          rm -rf node_modules package-lock.json
      
      - name: Install dependencies
        run: npm i
      
      - name: Install Rollup Dependency
        run: npm install rollup

      - name: Build
        run: npm run build

      - name: Start dev server
        run: npm run dev &
        env:
          PORT: 5174

      - name: Wait for dev server
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5174 > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            sleep 1
          done
          echo "Server failed to start"
          exit 1

      - name: Run tests
        run: npm test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release 